name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest"]
        
    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup Swift
      uses: YOCKOW/Action-setup-swift@v1.1.9
      with:
        swift-version: 5.3
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-test-discovery
